/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Acceuil_oumayma (void)
{
  GtkWidget *Acceuil_oumayma;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_acceuil_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *button_acceuil_modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_acceuil_chercher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *button_acceuil_afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button_acceuil_supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;

  Acceuil_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Acceuil_oumayma), _("Page d'acceuil"));
  gtk_window_set_default_size (GTK_WINDOW (Acceuil_oumayma), 600, 500);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Acceuil_oumayma), fixed1);

  label1 = gtk_label_new (_("Gestion du stock"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 264, 16);
  gtk_widget_set_size_request (label1, 184, 17);

  button_acceuil_ajouter = gtk_button_new ();
  gtk_widget_show (button_acceuil_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button_acceuil_ajouter, 88, 64);
  gtk_widget_set_size_request (button_acceuil_ajouter, 216, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_acceuil_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter un nouveau produit"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button_acceuil_modifier = gtk_button_new ();
  gtk_widget_show (button_acceuil_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), button_acceuil_modifier, 368, 64);
  gtk_widget_set_size_request (button_acceuil_modifier, 208, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_acceuil_modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier un produit"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_acceuil_chercher = gtk_button_new ();
  gtk_widget_show (button_acceuil_chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), button_acceuil_chercher, 88, 128);
  gtk_widget_set_size_request (button_acceuil_chercher, 216, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_acceuil_chercher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Chercher un produit "));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button_acceuil_afficher = gtk_button_new ();
  gtk_widget_show (button_acceuil_afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), button_acceuil_afficher, 216, 200);
  gtk_widget_set_size_request (button_acceuil_afficher, 224, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_acceuil_afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Affichage et gestion "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button_acceuil_supprimer = gtk_button_new ();
  gtk_widget_show (button_acceuil_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), button_acceuil_supprimer, 368, 128);
  gtk_widget_set_size_request (button_acceuil_supprimer, 208, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_acceuil_supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer un produit"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_acceuil_ajouter, "clicked",
                    G_CALLBACK (on_button_acceuil_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acceuil_modifier, "clicked",
                    G_CALLBACK (on_button_acceuil_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acceuil_chercher, "clicked",
                    G_CALLBACK (on_button_acceuil_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acceuil_afficher, "clicked",
                    G_CALLBACK (on_button_acceuil_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acceuil_supprimer, "clicked",
                    G_CALLBACK (on_button_acceuil_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Acceuil_oumayma, Acceuil_oumayma, "Acceuil_oumayma");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label1, "label1");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, button_acceuil_ajouter, "button_acceuil_ajouter");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, image1, "image1");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label2, "label2");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, button_acceuil_modifier, "button_acceuil_modifier");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, image2, "image2");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label3, "label3");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, button_acceuil_chercher, "button_acceuil_chercher");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, image5, "image5");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label6, "label6");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, button_acceuil_afficher, "button_acceuil_afficher");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, image3, "image3");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label4, "label4");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, button_acceuil_supprimer, "button_acceuil_supprimer");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, image4, "image4");
  GLADE_HOOKUP_OBJECT (Acceuil_oumayma, label5, "label5");

  return Acceuil_oumayma;
}

GtkWidget*
create_Ajouter_oumayma (void)
{
  GtkWidget *Ajouter_oumayma;
  GtkWidget *fixed2;
  GtkWidget *entry_ajouter_ref;
  GtkWidget *entry_ajouter_nom;
  GtkObject *spinbutton_ajouter_adj;
  GtkWidget *spinbutton_ajouter;
  GtkWidget *entry_ajouter_prix;
  GtkWidget *calendar_ajouter;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *combobox_ajouter;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *radiobutton_ajouter_basse;
  GSList *radiobutton_ajouter_basse_group = NULL;
  GtkWidget *radiobutton_ajouter_ambiante;
  GtkWidget *button_ajouter_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *button_retour_ajouter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label18;
  GtkWidget *button_voir_ajout;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *checkbutton_ajouter;

  Ajouter_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_oumayma), _("Ajouter"));
  gtk_window_set_default_size (GTK_WINDOW (Ajouter_oumayma), 600, 500);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter_oumayma), fixed2);

  entry_ajouter_ref = gtk_entry_new ();
  gtk_widget_show (entry_ajouter_ref);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_ajouter_ref, 160, 64);
  gtk_widget_set_size_request (entry_ajouter_ref, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajouter_ref), 8226);

  entry_ajouter_nom = gtk_entry_new ();
  gtk_widget_show (entry_ajouter_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_ajouter_nom, 160, 176);
  gtk_widget_set_size_request (entry_ajouter_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajouter_nom), 8226);

  spinbutton_ajouter_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_ajouter_adj), 1, 0);
  gtk_widget_show (spinbutton_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_ajouter, 168, 224);
  gtk_widget_set_size_request (spinbutton_ajouter, 60, 27);

  entry_ajouter_prix = gtk_entry_new ();
  gtk_widget_show (entry_ajouter_prix);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_ajouter_prix, 168, 280);
  gtk_widget_set_size_request (entry_ajouter_prix, 104, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajouter_prix), 8226);

  calendar_ajouter = gtk_calendar_new ();
  gtk_widget_show (calendar_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), calendar_ajouter, 408, 96);
  gtk_widget_set_size_request (calendar_ajouter, 192, 178);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_ajouter),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label7 = gtk_label_new (_("Ajouter un nouveau produit "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 232, 8);
  gtk_widget_set_size_request (label7, 232, 25);

  label8 = gtk_label_new (_("R\303\251f\303\251rence"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 48, 64);
  gtk_widget_set_size_request (label8, 104, 25);

  combobox_ajouter = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_ajouter, 160, 120);
  gtk_widget_set_size_request (combobox_ajouter, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("L\303\251gumes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("Fruits"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("Viande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("Poisson"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("Poulet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajouter), _("Boissons"));

  label9 = gtk_label_new (_("Type "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 72, 120);
  gtk_widget_set_size_request (label9, 56, 25);

  label10 = gtk_label_new (_("Nom"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 72, 176);
  gtk_widget_set_size_request (label10, 56, 25);

  label11 = gtk_label_new (_("Quantit\303\251"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 48, 224);
  gtk_widget_set_size_request (label11, 88, 25);

  label12 = gtk_label_new (_("Prix"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 80, 280);
  gtk_widget_set_size_request (label12, 48, 25);

  label14 = gtk_label_new (_("Date d'ajout"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 392, 64);
  gtk_widget_set_size_request (label14, 120, 25);

  label13 = gtk_label_new (_("Temp\303\251rature de\n conservation "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 24, 328);
  gtk_widget_set_size_request (label13, 136, 40);

  radiobutton_ajouter_basse = gtk_radio_button_new_with_mnemonic (NULL, _("Basse temp\303\251rature"));
  gtk_widget_show (radiobutton_ajouter_basse);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_ajouter_basse, 176, 328);
  gtk_widget_set_size_request (radiobutton_ajouter_basse, 168, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_ajouter_basse), radiobutton_ajouter_basse_group);
  radiobutton_ajouter_basse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_ajouter_basse));

  radiobutton_ajouter_ambiante = gtk_radio_button_new_with_mnemonic (NULL, _("Temp\303\251rature ambiante"));
  gtk_widget_show (radiobutton_ajouter_ambiante);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_ajouter_ambiante, 176, 360);
  gtk_widget_set_size_request (radiobutton_ajouter_ambiante, 184, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_ajouter_ambiante), radiobutton_ajouter_basse_group);
  radiobutton_ajouter_basse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_ajouter_ambiante));

  button_ajouter_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_ajouter, 264, 424);
  gtk_widget_set_size_request (button_ajouter_ajouter, 112, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_ajouter_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  button_retour_ajouter = gtk_button_new ();
  gtk_widget_show (button_retour_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_ajouter, 568, 16);
  gtk_widget_set_size_request (button_retour_ajouter, 136, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_retour_ajouter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Page d'acceuil"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  button_voir_ajout = gtk_button_new ();
  gtk_widget_show (button_voir_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_voir_ajout, 392, 424);
  gtk_widget_set_size_request (button_voir_ajout, 168, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_voir_ajout), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Voir l'ajout "));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);

  checkbutton_ajouter = gtk_check_button_new_with_mnemonic (_("Veuillez confirmer\n l'ajout"));
  gtk_widget_show (checkbutton_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_ajouter, 56, 416);
  gtk_widget_set_size_request (checkbutton_ajouter, 160, 40);

  g_signal_connect ((gpointer) radiobutton_ajouter_basse, "toggled",
                    G_CALLBACK (on_radiobutton_ajouter_basse_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_ajouter_ambiante, "toggled",
                    G_CALLBACK (on_radiobutton_ajouter_ambiante_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajouter, "clicked",
                    G_CALLBACK (on_button_retour_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_voir_ajout, "clicked",
                    G_CALLBACK (on_button_voir_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_oumayma, Ajouter_oumayma, "Ajouter_oumayma");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, entry_ajouter_ref, "entry_ajouter_ref");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, entry_ajouter_nom, "entry_ajouter_nom");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, spinbutton_ajouter, "spinbutton_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, entry_ajouter_prix, "entry_ajouter_prix");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, calendar_ajouter, "calendar_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label7, "label7");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label8, "label8");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, combobox_ajouter, "combobox_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label9, "label9");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, radiobutton_ajouter_basse, "radiobutton_ajouter_basse");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, radiobutton_ajouter_ambiante, "radiobutton_ajouter_ambiante");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, button_ajouter_ajouter, "button_ajouter_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, image6, "image6");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, button_retour_ajouter, "button_retour_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, image8, "image8");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label18, "label18");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, button_voir_ajout, "button_voir_ajout");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, image7, "image7");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, label16, "label16");
  GLADE_HOOKUP_OBJECT (Ajouter_oumayma, checkbutton_ajouter, "checkbutton_ajouter");

  return Ajouter_oumayma;
}

GtkWidget*
create_Afficher_oumayma (void)
{
  GtkWidget *Afficher_oumayma;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *label17;
  GtkWidget *button_retour_afficher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label21;
  GtkWidget *button_afficher_afficher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label19;
  GtkWidget *button_rupture;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label20;

  Afficher_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher_oumayma), _("Afficher"));
  gtk_window_set_default_size (GTK_WINDOW (Afficher_oumayma), 600, 500);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Afficher_oumayma), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 40, 104);
  gtk_widget_set_size_request (treeview1, 640, 216);

  label17 = gtk_label_new (_("Affichage et gestion "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 256, 16);
  gtk_widget_set_size_request (label17, 216, 24);

  button_retour_afficher = gtk_button_new ();
  gtk_widget_show (button_retour_afficher);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retour_afficher, 560, 24);
  gtk_widget_set_size_request (button_retour_afficher, 136, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_retour_afficher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Page d'acceuil"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox11), label21, FALSE, FALSE, 0);

  button_afficher_afficher = gtk_button_new ();
  gtk_widget_show (button_afficher_afficher);
  gtk_fixed_put (GTK_FIXED (fixed3), button_afficher_afficher, 304, 64);
  gtk_widget_set_size_request (button_afficher_afficher, 128, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_afficher_afficher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  button_rupture = gtk_button_new ();
  gtk_widget_show (button_rupture);
  gtk_fixed_put (GTK_FIXED (fixed3), button_rupture, 216, 344);
  gtk_widget_set_size_request (button_rupture, 232, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_rupture), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Rupture dans le stock "));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox10), label20, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_retour_afficher, "clicked",
                    G_CALLBACK (on_button_retour_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_afficher, "clicked",
                    G_CALLBACK (on_button_afficher_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rupture, "clicked",
                    G_CALLBACK (on_button_rupture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher_oumayma, Afficher_oumayma, "Afficher_oumayma");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, label17, "label17");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, button_retour_afficher, "button_retour_afficher");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, image11, "image11");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, label21, "label21");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, button_afficher_afficher, "button_afficher_afficher");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, image9, "image9");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, label19, "label19");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, button_rupture, "button_rupture");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, image10, "image10");
  GLADE_HOOKUP_OBJECT (Afficher_oumayma, label20, "label20");

  return Afficher_oumayma;
}

GtkWidget*
create_Modifier_oumayma (void)
{
  GtkWidget *Modifier_oumayma;
  GtkWidget *fixed4;
  GtkWidget *entry_modifier_ref;
  GtkWidget *entry_modifier_nom;
  GtkObject *spinbutton_modifier_adj;
  GtkWidget *spinbutton_modifier;
  GtkWidget *entry_modifier_prix;
  GtkWidget *calendar_modifier;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *button_modifier_consulter;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *radiobutton_modifier_basse;
  GSList *radiobutton_modifier_basse_group = NULL;
  GtkWidget *radiobutton_modifier_ambiante;
  GtkWidget *button_voir_modif;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label31;
  GtkWidget *button_modifier_modifier;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label30;
  GtkWidget *button_retour_modifier;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label32;
  GtkWidget *label33;

  Modifier_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_oumayma), _("Modifier"));
  gtk_window_set_default_size (GTK_WINDOW (Modifier_oumayma), 600, 500);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Modifier_oumayma), fixed4);

  entry_modifier_ref = gtk_entry_new ();
  gtk_widget_show (entry_modifier_ref);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_modifier_ref, 232, 64);
  gtk_widget_set_size_request (entry_modifier_ref, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modifier_ref), 8226);

  entry_modifier_nom = gtk_entry_new ();
  gtk_widget_show (entry_modifier_nom);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_modifier_nom, 224, 128);
  gtk_widget_set_size_request (entry_modifier_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modifier_nom), 8226);

  spinbutton_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_modifier_adj), 1, 0);
  gtk_widget_show (spinbutton_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_modifier, 232, 192);
  gtk_widget_set_size_request (spinbutton_modifier, 60, 27);

  entry_modifier_prix = gtk_entry_new ();
  gtk_widget_show (entry_modifier_prix);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_modifier_prix, 224, 248);
  gtk_widget_set_size_request (entry_modifier_prix, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modifier_prix), 8226);

  calendar_modifier = gtk_calendar_new ();
  gtk_widget_show (calendar_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar_modifier, 472, 144);
  gtk_widget_set_size_request (calendar_modifier, 192, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_modifier),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label22 = gtk_label_new (_("Modifier un produit "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 288, 16);
  gtk_widget_set_size_request (label22, 160, 24);

  label23 = gtk_label_new (_("R\303\251f\303\251rence "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 104, 64);
  gtk_widget_set_size_request (label23, 104, 25);

  button_modifier_consulter = gtk_button_new ();
  gtk_widget_show (button_modifier_consulter);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modifier_consulter, 416, 64);
  gtk_widget_set_size_request (button_modifier_consulter, 112, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_modifier_consulter), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Consulter "));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox12), label24, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("Nom "));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 144, 128);
  gtk_widget_set_size_request (label25, 57, 24);

  label26 = gtk_label_new (_("Quantit\303\251 "));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 136, 192);
  gtk_widget_set_size_request (label26, 80, 17);

  label27 = gtk_label_new (_("Prix "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 144, 256);
  gtk_widget_set_size_request (label27, 49, 17);

  label28 = gtk_label_new (_("Temp\303\251rature de\nConservation "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 64, 312);
  gtk_widget_set_size_request (label28, 152, 39);

  radiobutton_modifier_basse = gtk_radio_button_new_with_mnemonic (NULL, _("Basse temp\303\251rature"));
  gtk_widget_show (radiobutton_modifier_basse);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_modifier_basse, 240, 328);
  gtk_widget_set_size_request (radiobutton_modifier_basse, 176, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modifier_basse), radiobutton_modifier_basse_group);
  radiobutton_modifier_basse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modifier_basse));

  radiobutton_modifier_ambiante = gtk_radio_button_new_with_mnemonic (NULL, _("Temp\303\251rature ambiante "));
  gtk_widget_show (radiobutton_modifier_ambiante);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_modifier_ambiante, 240, 360);
  gtk_widget_set_size_request (radiobutton_modifier_ambiante, 200, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modifier_ambiante), radiobutton_modifier_basse_group);
  radiobutton_modifier_basse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modifier_ambiante));

  button_voir_modif = gtk_button_new ();
  gtk_widget_show (button_voir_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), button_voir_modif, 304, 408);
  gtk_widget_set_size_request (button_voir_modif, 176, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_voir_modif), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Voir la modification "));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox14), label31, FALSE, FALSE, 0);

  button_modifier_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modifier_modifier, 168, 408);
  gtk_widget_set_size_request (button_modifier_modifier, 112, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_modifier_modifier), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox13), label30, FALSE, FALSE, 0);

  button_retour_modifier = gtk_button_new ();
  gtk_widget_show (button_retour_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retour_modifier, 552, 16);
  gtk_widget_set_size_request (button_retour_modifier, 144, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_retour_modifier), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Page d'acceuil "));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox15), label32, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("Date d'ajout "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 480, 112);
  gtk_widget_set_size_request (label33, 112, 17);

  g_signal_connect ((gpointer) button_modifier_consulter, "clicked",
                    G_CALLBACK (on_button_modifier_consulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modifier_basse, "toggled",
                    G_CALLBACK (on_radiobutton_modifier_basse_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modifier_ambiante, "toggled",
                    G_CALLBACK (on_radiobutton_modifier_ambiante_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_voir_modif, "clicked",
                    G_CALLBACK (on_button_voir_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_modifier, "clicked",
                    G_CALLBACK (on_button_retour_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_oumayma, Modifier_oumayma, "Modifier_oumayma");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, entry_modifier_ref, "entry_modifier_ref");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, entry_modifier_nom, "entry_modifier_nom");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, spinbutton_modifier, "spinbutton_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, entry_modifier_prix, "entry_modifier_prix");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, calendar_modifier, "calendar_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label23, "label23");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, button_modifier_consulter, "button_modifier_consulter");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, image12, "image12");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label24, "label24");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label25, "label25");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label26, "label26");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label27, "label27");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label28, "label28");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, radiobutton_modifier_basse, "radiobutton_modifier_basse");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, radiobutton_modifier_ambiante, "radiobutton_modifier_ambiante");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, button_voir_modif, "button_voir_modif");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, image14, "image14");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label31, "label31");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, button_modifier_modifier, "button_modifier_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, image13, "image13");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label30, "label30");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, button_retour_modifier, "button_retour_modifier");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, image15, "image15");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label32, "label32");
  GLADE_HOOKUP_OBJECT (Modifier_oumayma, label33, "label33");

  return Modifier_oumayma;
}

GtkWidget*
create_Chercher_oumayma (void)
{
  GtkWidget *Chercher_oumayma;
  GtkWidget *fixed5;
  GtkWidget *entry_chercher_ref;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *button_chercher_chercher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *label42;
  GtkWidget *button_retour_chercher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label43;
  GtkWidget *chercher_prix;
  GtkWidget *chercher_nom;
  GtkWidget *chercher_type;
  GtkWidget *chercher_quantite;
  GtkWidget *chercher_date;
  GtkWidget *chercher_temperature;

  Chercher_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Chercher_oumayma), _("Chercher"));
  gtk_window_set_default_size (GTK_WINDOW (Chercher_oumayma), 600, 500);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Chercher_oumayma), fixed5);

  entry_chercher_ref = gtk_entry_new ();
  gtk_widget_show (entry_chercher_ref);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_chercher_ref, 248, 72);
  gtk_widget_set_size_request (entry_chercher_ref, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chercher_ref), 8226);

  label34 = gtk_label_new (_("Chercher un produit "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 264, 16);
  gtk_widget_set_size_request (label34, 200, 25);

  label35 = gtk_label_new (_("R\303\251f\303\251rence "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 136, 72);
  gtk_widget_set_size_request (label35, 96, 25);

  button_chercher_chercher = gtk_button_new ();
  gtk_widget_show (button_chercher_chercher);
  gtk_fixed_put (GTK_FIXED (fixed5), button_chercher_chercher, 440, 72);
  gtk_widget_set_size_request (button_chercher_chercher, 104, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_chercher_chercher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Chercher "));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox16), label36, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("Nom "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 176, 144);
  gtk_widget_set_size_request (label37, 49, 17);

  label38 = gtk_label_new (_("Type "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 176, 192);
  gtk_widget_set_size_request (label38, 49, 17);

  label39 = gtk_label_new (_("Quantit\303\251"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 160, 240);
  gtk_widget_set_size_request (label39, 80, 16);

  label41 = gtk_label_new (_("Prix "));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed5), label41, 176, 288);
  gtk_widget_set_size_request (label41, 49, 17);

  label40 = gtk_label_new (_("Date d'ajout "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed5), label40, 128, 328);
  gtk_widget_set_size_request (label40, 120, 16);

  label42 = gtk_label_new (_("Temp\303\251rature de\nconservation "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed5), label42, 120, 368);
  gtk_widget_set_size_request (label42, 136, 39);

  button_retour_chercher = gtk_button_new ();
  gtk_widget_show (button_retour_chercher);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retour_chercher, 552, 16);
  gtk_widget_set_size_request (button_retour_chercher, 144, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_retour_chercher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Page d'acceuil "));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox17), label43, FALSE, FALSE, 0);

  chercher_prix = gtk_label_new ("");
  gtk_widget_show (chercher_prix);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_prix, 296, 288);
  gtk_widget_set_size_request (chercher_prix, 152, 25);

  chercher_nom = gtk_label_new ("");
  gtk_widget_show (chercher_nom);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_nom, 296, 136);
  gtk_widget_set_size_request (chercher_nom, 144, 25);

  chercher_type = gtk_label_new ("");
  gtk_widget_show (chercher_type);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_type, 296, 192);
  gtk_widget_set_size_request (chercher_type, 144, 25);

  chercher_quantite = gtk_label_new ("");
  gtk_widget_show (chercher_quantite);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_quantite, 296, 232);
  gtk_widget_set_size_request (chercher_quantite, 160, 25);

  chercher_date = gtk_label_new ("");
  gtk_widget_show (chercher_date);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_date, 288, 320);
  gtk_widget_set_size_request (chercher_date, 168, 25);

  chercher_temperature = gtk_label_new ("");
  gtk_widget_show (chercher_temperature);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_temperature, 296, 368);
  gtk_widget_set_size_request (chercher_temperature, 168, 32);

  g_signal_connect ((gpointer) button_chercher_chercher, "clicked",
                    G_CALLBACK (on_button_chercher_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_chercher, "clicked",
                    G_CALLBACK (on_button_retour_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Chercher_oumayma, Chercher_oumayma, "Chercher_oumayma");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, entry_chercher_ref, "entry_chercher_ref");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label34, "label34");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label35, "label35");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, button_chercher_chercher, "button_chercher_chercher");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, image16, "image16");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label36, "label36");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label37, "label37");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label38, "label38");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label39, "label39");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label41, "label41");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label40, "label40");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label42, "label42");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, button_retour_chercher, "button_retour_chercher");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, image17, "image17");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, label43, "label43");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_prix, "chercher_prix");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_nom, "chercher_nom");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_type, "chercher_type");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_quantite, "chercher_quantite");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_date, "chercher_date");
  GLADE_HOOKUP_OBJECT (Chercher_oumayma, chercher_temperature, "chercher_temperature");

  return Chercher_oumayma;
}

GtkWidget*
create_Supprimer_oumayma (void)
{
  GtkWidget *Supprimer_oumayma;
  GtkWidget *fixed6;
  GtkWidget *entry_supprimer_ref;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *button_supprimer_supprimer;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label46;
  GtkWidget *button_voir_supprimer;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label47;
  GtkWidget *button_retour_supprimer;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label48;

  Supprimer_oumayma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer_oumayma), _("Supprimer"));
  gtk_window_set_default_size (GTK_WINDOW (Supprimer_oumayma), 600, 500);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Supprimer_oumayma), fixed6);

  entry_supprimer_ref = gtk_entry_new ();
  gtk_widget_show (entry_supprimer_ref);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_supprimer_ref, 232, 120);
  gtk_widget_set_size_request (entry_supprimer_ref, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_supprimer_ref), 8226);

  label44 = gtk_label_new (_("Supprimer un produit "));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 288, 24);
  gtk_widget_set_size_request (label44, 160, 24);

  label45 = gtk_label_new (_("R\303\251f\303\251rence "));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 88, 120);
  gtk_widget_set_size_request (label45, 104, 25);

  button_supprimer_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), button_supprimer_supprimer, 424, 120);
  gtk_widget_set_size_request (button_supprimer_supprimer, 112, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_supprimer_supprimer), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox18), label46, FALSE, FALSE, 0);

  button_voir_supprimer = gtk_button_new ();
  gtk_widget_show (button_voir_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), button_voir_supprimer, 224, 208);
  gtk_widget_set_size_request (button_voir_supprimer, 176, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_voir_supprimer), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Voir la suppression "));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox19), label47, FALSE, FALSE, 0);

  button_retour_supprimer = gtk_button_new ();
  gtk_widget_show (button_retour_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retour_supprimer, 568, 32);
  gtk_widget_set_size_request (button_retour_supprimer, 128, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_retour_supprimer), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Page d'acceuil "));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox20), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supprimer_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_voir_supprimer, "clicked",
                    G_CALLBACK (on_button_voir_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_supprimer, "clicked",
                    G_CALLBACK (on_button_retour_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_oumayma, Supprimer_oumayma, "Supprimer_oumayma");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, entry_supprimer_ref, "entry_supprimer_ref");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, label44, "label44");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, label45, "label45");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, button_supprimer_supprimer, "button_supprimer_supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, image18, "image18");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, label46, "label46");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, button_voir_supprimer, "button_voir_supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, image19, "image19");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, label47, "label47");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, button_retour_supprimer, "button_retour_supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, image20, "image20");
  GLADE_HOOKUP_OBJECT (Supprimer_oumayma, label48, "label48");

  return Supprimer_oumayma;
}

