/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Acceuil_oumayma (void);
GtkWidget* create_Ajouter_oumayma (void);
GtkWidget* create_Afficher_oumayma (void);
GtkWidget* create_Modifier_oumayma (void);
GtkWidget* create_Chercher_oumayma (void);
GtkWidget* create_Supprimer_oumayma (void);
