/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Acceuil_oumayma;
  GtkWidget *Ajouter_oumayma;
  GtkWidget *Afficher_oumayma;
  GtkWidget *Modifier_oumayma;
  GtkWidget *Chercher_oumayma;
  GtkWidget *Supprimer_oumayma;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Acceuil_oumayma = create_Acceuil_oumayma ();
  gtk_widget_show (Acceuil_oumayma);
  Ajouter_oumayma = create_Ajouter_oumayma ();
  gtk_widget_show (Ajouter_oumayma);
  Afficher_oumayma = create_Afficher_oumayma ();
  gtk_widget_show (Afficher_oumayma);
  Modifier_oumayma = create_Modifier_oumayma ();
  gtk_widget_show (Modifier_oumayma);
  Chercher_oumayma = create_Chercher_oumayma ();
  gtk_widget_show (Chercher_oumayma);
  Supprimer_oumayma = create_Supprimer_oumayma ();
  gtk_widget_show (Supprimer_oumayma);

  gtk_main ();
  return 0;
}

